"""first migration

Revision ID: 3283690c2880
Revises: 
Create Date: 2022-03-05 21:38:24.146241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3283690c2880'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('current_crypto', sa.String(length=5), nullable=True),
    sa.Column('current_pair', sa.String(length=5), nullable=True),
    sa.Column('current_market', sa.String(length=10), nullable=True),
    sa.Column('current_market_name', sa.String(length=30), nullable=True),
    sa.Column('current_platform', sa.String(length=20), nullable=True),
    sa.Column('speak', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    # ### end Alembic commands ###
