"""first migration

Revision ID: 46918f22078c
Revises: 
Create Date: 2021-03-23 00:08:16.020164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46918f22078c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('current_market', sa.String(length=10), nullable=True),
    sa.Column('current_market_name', sa.String(length=30), nullable=True),
    sa.Column('current_platform', sa.String(length=20), nullable=True),
    sa.Column('speak', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('current_price', sa.Float(precision='10,2'), nullable=False),
    sa.Column('max_price', sa.Float(precision='10,2'), nullable=False),
    sa.Column('min_price', sa.Float(precision='10,2'), nullable=False),
    sa.Column('max_date', sa.DateTime(), nullable=True),
    sa.Column('min_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('account_id', sa.BIGINT(), nullable=True),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(precision='10,2'), nullable=False),
    sa.Column('comission', sa.Float(precision='10,2'), nullable=False),
    sa.Column('cuantity', sa.Float(precision='10,2'), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position')
    op.drop_table('trade')
    op.drop_table('account')
    # ### end Alembic commands ###
