"""update account, add crypto and pair

Revision ID: 916e788e7bf7
Revises: 46918f22078c
Create Date: 2022-02-06 15:43:13.221576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '916e788e7bf7'
down_revision = '46918f22078c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_id', table_name='market')
    op.drop_table('market')
    op.add_column('account', sa.Column('current_crypto', sa.String(length=5), nullable=True))
    op.add_column('account', sa.Column('current_pair', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'current_pair')
    op.drop_column('account', 'current_crypto')
    op.create_table('market',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('open', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('high', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('low', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('close', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('volume', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('close_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('quote_av', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('trades', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('tb_base_av', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('tb_quote_av', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('pair', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('macd1', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('macd2', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('diference', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('regime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('market', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('strategy', mysql.DOUBLE(asdecimal=True), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_market_id', 'market', ['id'], unique=False)
    # ### end Alembic commands ###
